import{a as L,i as l}from"./assets/vendor-4yCzdkXl.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&c(m)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const S=async(r,e)=>await L.get(`https://newsapi.org/v2/everything?q=${r}&apiKey=ee921bec82754786b568b8b5c41f6003&pageSize=15&page=${e}`),v=async(r,e)=>await L.get(`https://newsapi.org/v2/everything?q=${r}&apiKey=ee921bec82754786b568b8b5c41f6003&pageSize=15&page=${e}&sortBy=publishedAt`),b=r=>`
    <li class="article-item">
        <a class="aricle-title" href="${r.url}" target="_blank">${r.title} - ${r.author}</a>

        <img class="article-image" src="${r.urlToImage}" alt="news-image">

        <p class="article-description">${r.description}</p>
        <p class="article-content">${r.content}</p>

        <p class="article-date">${r.publishedAt}</p>
    </li>
    `,w=document.querySelector(".news-form"),E=document.querySelector(".news-input");document.querySelector(".search-news-btn");const g=document.querySelector(".news-list"),n=document.querySelector(".load-more-btn"),p=document.querySelector(".loader"),y=document.querySelector(".loader-more"),h=document.querySelector("#theme-switch");let f=!1;const q=r=>{console.log(h.checked),h.checked?f=!0:f=!1};h.addEventListener("click",q);let i=1,d,a;const $=async r=>{if(r.preventDefault(),d===""){l.error({title:"Error",titleSize:"35",message:"Please fill the gap!",messageSize:"30",position:"bottomRight"});return}try{n.classList.add("is-hidden"),i=1,d=E.value.trim(),p.classList.remove("hidden");let e;if(f?e=await v(d,i):e=await S(d,i),p.classList.add("hidden"),e.data.totalResults===0){l.error({title:"Error",titleSize:"25",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"15",position:"bottomRight"});return}console.log(e.data.articles),g.innerHTML="";const s=[];if(e.data.articles.forEach(c=>{s.push(b(c))}),console.log(s),g.insertAdjacentHTML("beforeend",s.join("")),window.scrollBy({top:500,left:0,behavior:"smooth"}),a=Math.ceil(e.data.totalResults/s.length),l.success({message:`Sucess! ${a*s.length} news are found!`,messageSize:"30",position:"bottomRight"}),a<=1)return;if(i<=a){if(i===a){loadMoreBtn.classList.add("is-hidden"),n.addEventListener("click",u);return}n.classList.remove("is-hidden"),n.removeEventListener("click",u),n.addEventListener("click",u)}}catch(e){l.error({message:"Sorry! Something went wrong(",messageSize:"30",position:"bottomRight"}),console.log(e);return}},u=async r=>{try{i++,console.log(i),y.classList.remove("hidden");const e=await S(d,i);y.classList.add("hidden");const s=[];e.data.articles.forEach(o=>{s.push(b(o))}),g.insertAdjacentHTML("beforeend",s.join(""));const t=document.querySelector(".article-item").getBoundingClientRect();if(window.scrollBy({top:t.height,left:0,behavior:"smooth"}),i===a){l.info({title:"",titleSize:"25",message:"We're sorry, but you've reached the end of search results.",messageSize:"20",position:"bottomRight"}),n.classList.add("is-hidden"),n.removeEventListener("click",u);return}}catch(e){console.log(e)}};w.addEventListener("submit",$);
//# sourceMappingURL=index.js.map
