import{a as m,i as u}from"./assets/vendor-4yCzdkXl.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const y of o.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&i(y)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const S=async(t,e)=>await m.get(`https://newsapi.org/v2/everything?q=${t}&apiKey=ee921bec82754786b568b8b5c41f6003&pageSize=15&page=${e}`),E=async(t,e)=>await m.get(`https://newsapi.org/v2/everything?q=${t}&apiKey=ee921bec82754786b568b8b5c41f6003&pageSize=15&page=${e}&sortBy=publishedAt`),$=async(t,e,s)=>await m.get(`https://newsapi.org/v2/top-headlines?q=${t}&apiKey=ee921bec82754786b568b8b5c41f6003&pageSize=15&page=${e}&category=${s}`),q=async(t,e,s)=>await m.get(`https://newsapi.org/v2/top-headlines?q=${t}&apiKey=ee921bec82754786b568b8b5c41f6003&pageSize=15&page=${e}&sortBy=publishedAt&category=${s}`),L=t=>`
    <li class="article-item">
        <a class="aricle-title" href="${t.url}" target="_blank">${t.title} - ${t.author}</a>

        <img class="article-image" src="${t.urlToImage}" alt="news-image">

        <p class="article-description">${t.description}</p>
        <p class="article-content">${t.content}</p>

        <p class="article-date">${t.publishedAt}</p>
    </li>
    `,z=document.querySelector(".news-form"),B=document.querySelector(".news-input");document.querySelector(".search-news-btn");const p=document.querySelector(".news-list"),c=document.querySelector(".load-more-btn"),b=document.querySelector(".loader"),w=document.querySelector(".loader-more"),f=document.querySelector("#theme-switch");let h=!1;const D=t=>{console.log(f.checked),f.checked?h=!0:h=!1};f.addEventListener("click",D);const v=document.querySelector(".category-select");let d="default";v.addEventListener("input",t=>{d=v.value,console.log(d)});let a=1,n,l;const M=async t=>{if(t.preventDefault(),c.classList.add("is-hidden"),a=1,n=B.value.trim(),n===""){u.error({title:"Error",titleSize:"35",message:"Please fill the gap!",messageSize:"30",position:"bottomRight"});return}try{b.classList.remove("hidden");let e;if(h&&d!=="default"?e=await q(n,a,d):h?e=await E(n,a):d!=="default"?e=await $(n,a,d):e=await S(n,a),b.classList.add("hidden"),e.data.totalResults===0){u.error({title:"Error",titleSize:"25",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"15",position:"bottomRight"});return}console.log(e.data.articles),p.innerHTML="";const s=[];if(e.data.articles.forEach(i=>{s.push(L(i))}),console.log(s),p.insertAdjacentHTML("beforeend",s.join("")),window.scrollBy({top:500,left:0,behavior:"smooth"}),l=Math.ceil(e.data.totalResults/s.length),u.success({message:`Sucess! ${l*s.length} news are found!`,messageSize:"30",position:"bottomRight"}),l<=1)return;if(a<=l){if(a===l){loadMoreBtn.classList.add("is-hidden"),c.addEventListener("click",g);return}c.classList.remove("is-hidden"),c.removeEventListener("click",g),c.addEventListener("click",g)}}catch(e){u.error({message:"Sorry! Something went wrong(",messageSize:"30",position:"bottomRight"}),console.log(e);return}},g=async t=>{try{a++,console.log(a),w.classList.remove("hidden");const e=await S(n,a);w.classList.add("hidden");const s=[];e.data.articles.forEach(o=>{s.push(L(o))}),p.insertAdjacentHTML("beforeend",s.join(""));const r=document.querySelector(".article-item").getBoundingClientRect();if(window.scrollBy({top:r.height,left:0,behavior:"smooth"}),a===l){u.info({title:"",titleSize:"25",message:"We're sorry, but you've reached the end of search results.",messageSize:"20",position:"bottomRight"}),c.classList.add("is-hidden"),c.removeEventListener("click",g);return}}catch(e){console.log(e)}};z.addEventListener("submit",M);
//# sourceMappingURL=index.js.map
