import{a as p,i as l}from"./assets/vendor-4yCzdkXl.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&c(m)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const f=async(r,t)=>await p.get(`https://newsapi.org/v2/everything?q=${r}&apiKey=ee921bec82754786b568b8b5c41f6003&pageSize=15&page=${t}`,{headers:{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}}),h=r=>`
    <li class="article-item">
        <a class="aricle-title" href="${r.url}" target="_blank">${r.title} - ${r.author}</a>

        <img class="article-image" src="${r.urlToImage}" alt="news-image">

        <p class="article-description">${r.description}</p>
        <p class="article-content">${r.content}</p>

        <p class="article-date">${r.publishedAt}</p>
    </li>
    `,y=document.querySelector(".news-form"),L=document.querySelector(".news-input");document.querySelector(".search-news-btn");const g=document.querySelector(".news-list"),n=document.querySelector(".load-more-btn");let i=1,d,a;const S=async r=>{if(r.preventDefault(),d===""){l.error({title:"Error",titleSize:"35",message:"Please fill the gap!",messageSize:"30",position:"bottomRight"});return}try{n.classList.add("is-hidden"),i=1,d=L.value.trim();const t=await f(d,i);if(t.data.totalResults===0){l.error({title:"Error",titleSize:"25",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"15",position:"bottomRight"});return}console.log(t.data.articles),g.innerHTML="";const s=[];if(t.data.articles.forEach(c=>{s.push(h(c))}),console.log(s),g.insertAdjacentHTML("beforeend",s.join("")),window.scrollBy({top:500,left:0,behavior:"smooth"}),a=Math.ceil(t.data.totalResults/s.length),l.success({message:`Sucess! ${a*s.length} news are found!`,messageSize:"30",position:"bottomRight"}),a<=1)return;if(i<=a){if(i===a){loadMoreBtn.classList.add("is-hidden"),n.addEventListener("click",u);return}n.classList.remove("is-hidden"),n.removeEventListener("click",u),n.addEventListener("click",u)}}catch(t){l.error({message:"Sorry! Something went wrong(",messageSize:"30",position:"bottomRight"}),console.log(t);return}},u=async r=>{try{i++,console.log(i);const t=await f(d,i),s=[];t.data.articles.forEach(o=>{s.push(h(o))}),g.insertAdjacentHTML("beforeend",s.join(""));const e=document.querySelector(".article-item").getBoundingClientRect();if(window.scrollBy({top:e.height,left:0,behavior:"smooth"}),i===a){l.info({title:"",titleSize:"25",message:"We're sorry, but you've reached the end of search results.",messageSize:"20",position:"bottomRight"}),n.classList.add("is-hidden"),n.removeEventListener("click",u);return}}catch(t){console.log(t)}};y.addEventListener("submit",S);
//# sourceMappingURL=index.js.map
