/* empty css                      */import{i as g}from"./assets/vendor-I1I71QQ2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function e(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(o){if(o.ep)return;o.ep=!0;const n=e(o);fetch(o.href,n)}})();//! =============================== Отримання списку постів (GET) ===============================
const S=document.querySelector(".posts-container"),w=document.querySelector(".get-post-btn");document.querySelector(".post-container");const i=document.querySelector(".user-id-input"),E=document.querySelector(".get-info-btn"),u=document.querySelector(".post-title-input"),d=document.querySelector(".post-content-input"),L=document.querySelector(".create-btn"),p=document.querySelector(".post-title-update"),f=document.querySelector(".post-content-update"),m=document.querySelector(".update-id-input"),q=document.querySelector(".update-btn"),h=document.querySelector(".post-id-delete"),$=document.querySelector(".delete-btn"),a=document.querySelector(".load-btn");a.classList.add("is-hidden");let y=[],v=1,P=[];const c=r=>{fetch(`https://67911779af8442fd7378ff4e.mockapi.io/UserPosts?limit=10&page=${v}`).then(t=>{if(!t.ok)throw new Error(t.status);return a.classList.add("is-hidden"),t.json()}).then(t=>{y=[],P=[],S.innerHTML="",t.forEach(e=>{y.push(`
                    <div class="post-container">
                        <h2 class="post-title">${e.title} - ${e.author}</h2>
                        <p class="post-content">${e.content}</p>
                        <p class="post-id">POST ID:${e.id}</p>
                    </div>
                    `),P.push(`
                    <div class="post-container">
                        <h2 class="post-title">${e.title} - ${e.author}</h2>
                        <p class="post-content">${e.content}</p>
                        <p class="post-id">POST ID:${e.id}</p>
                    </div>
                    `)}),S.insertAdjacentHTML("beforeend",y.join("")),a.classList.remove("is-hidden")})};w.addEventListener("click",c);a.addEventListener("click",r=>{v++,console.log(v),c()});//! =============================== Отримання інформації про користувача за ID ===============================
const O=async r=>{try{const t=await fetch(`https://67911779af8442fd7378ff4e.mockapi.io/UserPosts/${r}`);if(!t.ok)throw new Error(t.status);const e=await t.json();return{name:e.author,email:e.email}}catch(t){console.log(t)}};E.addEventListener("click",async r=>{if(i.value.trim()!=="")try{const t=await O(i.value.trim());i.value="",g.info({timeout:7e3,overlay:!0,title:"User Info:",titleSize:"55",message:`Name: ${t.name} | Email: ${t.email}`,messageSize:"50",position:"center",drag:!1}),i.value=""}catch{g.error({timeout:2e3,overlay:!0,title:"Error",titleSize:"55",message:"User is not found!",messageSize:"50",position:"center",drag:!1})}});//! =============================== Створення нового поста (POST) ===============================
const b=r=>{try{const t={method:"POST",body:JSON.stringify(r),headers:{"Content-Type":"application/json"}};return fetch("https://67911779af8442fd7378ff4e.mockapi.io/UserPosts",t).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}catch(t){console.log(t)}};L.addEventListener("click",async r=>{if(!(u.value.trim()===""||d.value.trim()===""))try{const t={author:"Alex",email:"test@gmail.com",title:`${u.value}`,content:`${d.value}`},e=await b(t);u.value="",d.value="",c()}catch(t){console.log(t)}});//! =============================== Оновлення поста (PUT) ===============================
const k=(r,t,e)=>{try{const o={method:"PUT",body:JSON.stringify({title:t,content:e}),headers:{"Content-Type":"application/json"}};fetch(`https://67911779af8442fd7378ff4e.mockapi.io/UserPosts/${r}`,o).then(n=>{if(!n.ok)throw new Error(n.status);return n.json()})}catch(s){console.log(s)}};q.addEventListener("click",async r=>{if(!(m.value.trim()===""||p.value.trim()===""||f.value.trim()===""))try{const t=await k(m.value.trim(),p.value.trim(),f.value.trim());m.value="",p.value="",f.value="",c()}catch(t){console.log(t)}});//! =============================== Видалення поста (DELETE) ===============================
const T=r=>{const t={method:"DELETE"};return fetch(`https://67911779af8442fd7378ff4e.mockapi.io/UserPosts/${r}/`,t).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).catch(e=>{console.log(e)})};$.addEventListener("click",async r=>{if(h.value.trim()!=="")try{const t=await T(h.value.trim());h.value="",c()}catch(t){console.log(t)}});
//# sourceMappingURL=task-1.js.map
